const express=require("express"),fs=require("fs"),path=require("path"),db=require("../db");
const auth=require("../middleware/auth"),adminOnly=require("../middleware/adminOnly");
const {nftUpload,uploadDir}=require("../middleware/nftUpload");
const adminRouter=express.Router(),userRouter=express.Router();
const present=(req,nft)=>({...nft,image_url:nft.image_filename?`${req.protocol}://${req.get("host")}/uploads/nfts/${encodeURIComponent(nft.image_filename)}`:null});
const payload=body=>({name:String(body.name||"").trim(),collection:String(body.collection_name||"").trim(),description:String(body.description||"").trim(),network:String(body.network||"").trim(),tokenId:String(body.token_id||"").trim(),wallet:String(body.mint_wallet_address||"").trim(),value:String(body.current_value??"").trim(),currency:String(body.currency_symbol||"$").trim()||"$",active:body.is_active===undefined||["1","true","on"].includes(String(body.is_active).toLowerCase())?1:0});
function invalid(data,needsImage,file){if(data.name.length<2||data.name.length>150)return"NFT name must be 2–150 characters.";if(!data.network||data.network.length>80)return"Enter a valid network.";if(data.wallet.length<8||data.wallet.length>255)return"Enter a valid minting wallet address.";if(!/^\d{1,18}(\.\d{1,2})?$/.test(data.value))return"Enter a valid value with up to 2 decimals.";if(data.currency.length>8||data.collection.length>150||data.description.length>1000||data.tokenId.length>191)return"One or more fields are too long.";if(needsImage&&!file)return"An NFT image is required.";return""}
adminRouter.get("/",auth,adminOnly,async(req,res)=>{try{const[rows]=await db.query("SELECT * FROM nft_assets ORDER BY id DESC");res.json({nfts:rows.map(row=>present(req,row)),count:rows.length})}catch(error){console.error("[admin.nfts.list]",error);res.status(500).json({message:"Unable to load NFT assets"})}});
adminRouter.post("/",auth,adminOnly,nftUpload.single("image"),async(req,res)=>{const data=payload(req.body),error=invalid(data,true,req.file);if(error)return res.status(400).json({message:error});try{const[result]=await db.query("INSERT INTO nft_assets (name,collection_name,description,network,token_id,mint_wallet_address,current_value,currency_symbol,image_filename,is_active,created_by) VALUES (?,?,?,?,?,?,?,?,?,?,?)",[data.name,data.collection||null,data.description||null,data.network,data.tokenId||null,data.wallet,data.value,data.currency,req.file.filename,data.active,req.user.id]);res.status(201).json({message:"NFT asset published",nft_id:result.insertId})}catch(error){console.error("[admin.nfts.create]",error);res.status(500).json({message:"Unable to publish NFT asset"})}});
adminRouter.put("/:id",auth,adminOnly,nftUpload.single("image"),async(req,res)=>{const id=Number(req.params.id),data=payload(req.body),error=!Number.isSafeInteger(id)||id<1?"Invalid NFT id.":invalid(data,false,req.file);if(error)return res.status(400).json({message:error});try{const[rows]=await db.query("SELECT image_filename FROM nft_assets WHERE id=? LIMIT 1",[id]);if(!rows.length)return res.status(404).json({message:"NFT asset not found"});const filename=req.file?.filename||rows[0].image_filename;await db.query("UPDATE nft_assets SET name=?,collection_name=?,description=?,network=?,token_id=?,mint_wallet_address=?,current_value=?,currency_symbol=?,image_filename=?,is_active=? WHERE id=?",[data.name,data.collection||null,data.description||null,data.network,data.tokenId||null,data.wallet,data.value,data.currency,filename,data.active,id]);if(req.file&&rows[0].image_filename)fs.unlink(path.join(uploadDir,rows[0].image_filename),()=>{});res.json({message:"NFT asset updated"})}catch(error){console.error("[admin.nfts.update]",error);res.status(500).json({message:"Unable to update NFT asset"})}});
adminRouter.delete("/:id",auth,adminOnly,async(req,res)=>{const id=Number(req.params.id);if(!Number.isSafeInteger(id)||id<1)return res.status(400).json({message:"Invalid NFT id."});try{const[rows]=await db.query("SELECT image_filename FROM nft_assets WHERE id=? LIMIT 1",[id]);if(!rows.length)return res.status(404).json({message:"NFT asset not found"});await db.query("DELETE FROM nft_assets WHERE id=?",[id]);if(rows[0].image_filename)fs.unlink(path.join(uploadDir,rows[0].image_filename),()=>{});res.json({message:"NFT asset deleted"})}catch(error){console.error("[admin.nfts.delete]",error);res.status(500).json({message:"Unable to delete NFT asset"})}});
adminRouter.use((error,_req,res,_next)=>res.status(400).json({message:error.message||"Unable to upload NFT image"}));
userRouter.get("/",auth,async(req,res)=>{try{const[rows]=await db.query("SELECT id,name,collection_name,description,network,token_id,mint_wallet_address,current_value,currency_symbol,image_filename,created_at FROM nft_assets WHERE is_active=1 ORDER BY id DESC");res.json({nfts:rows.map(row=>present(req,row)),count:rows.length,total_value:rows.reduce((sum,row)=>sum+Number(row.current_value||0),0)})}catch(error){console.error("[users.nfts.list]",error);res.status(500).json({message:"Unable to load NFT assets"})}});
module.exports={adminRouter,userRouter};
